### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'README.markdown'

### ISSUE THREAD

**Issue by bugsnif** [synodriver/pytea#3]
pip install -U pytea2
Requirement already satisfied: pytea2 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (0.1.1)                                         Collecting pytea2
  Using cached pytea2-0.2.0.tar.gz (131 kB)         Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
                                                    × python setup.py egg_info did not run successfully.
  │ exit code: 1                                    ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>              File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-install-l1iryz45/pytea2_1c42d772e699424d9d7129105d97d7ef/setup.py", line 93, in <module>
          main()
        File "/data/data/com.termux/files/usr/tmp/pip-install-l1iryz45/pytea2_1c42d772e699424d9d7129105d97d7ef/setup.py", line 55, in main
          dis = get_dis()                                 File "/data/data/com.termux/files/usr/tmp/pip-install-l1iryz45/pytea2_1c42d772e699424d9d7129105d97d7ef/setup.py", line 45, in get_dis
          with open("README.markdown", "r", encoding="utf-8") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'README.markdown'
      [end of output]                             
  note: This error originates from a subprocess, and is likely not a problem with pip.              error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.                                                                           note: This is an issue with the package mentioned above, not pip.                                   hint: See above for details.

**Comment by synodriver** [comment]
What's your operating system? I've already build binary wheels for all platforms. Besides, in order to compile from source, you will need to install cython and a c compiler. Using ```git clone https://github.com/synodriver/pytea.git``` and ```python setup.py sdist bdist_wheel``` to build.

**Comment by synodriver** [comment]
Besides, this is ```tencent version``` of tea. Meaning the format is slightly different from the normal one.
